#ここにライブラリとして記述する
#start.rbに入れました

class Click_coffee
  constructor: (@object) ->
    alert @object
    alert "start.rbで実行してるんやで"
  story1: ->
    $(@object).click =>
      alert @object
      alert 123
###
aa = new TestCtrl ("#btn12")
aa.story1()
###   
# rakefileでやりました

######TestCtrlの中身######
# ここからTestCtrlの中身ですね
class TestCtrl
  constructor: ->
    #alert "okべいび"
    
  story1: ->
    alert "story1です"
  
  story2: ->
    ###
    document.addEventListener("deviceready", onDeviceReady, false)
    db = window.openDatabase("database", "1.0", "testdatabase", 1000000);
    ###
    name = 'localdb'
    version = '1.0'
    description = 'Web SQL Database'
    size = 2 * 1024 * 1024
    db = openDatabase(name, version, description, size)
    
    db.transaction (tx) ->
      tx.executeSql 'insert into user (id, name) values (?, ?)', [1, '金田']
  
  story3: ->



######################################
#表示させるクラス
class Disp
  constructor: (@id) ->
  disp: (@str) ->
    document.getElementById(@id).innerHTML=@str

  add: (@str) ->
      newDiv = document.createElement("div")
      newDiv.innerHTML = @str
      my_div = document.getElementById("org_div1")
      document.getElementById(@id).insertBefore(newDiv, my_div)

  delete: ->
      document.getElementById(@id).innerHTML=""
  
  # ---
  # generated by js2coffee 2.2.0
  
#################################
#ローカルストレージのキーを入れると+マイナスできるクラス
class Cpm
  constructor:(@id) ->
  plus: ->
    getstr = localStorage.getItem(@id)
    num = parseInt(getstr, 10)
    if isNaN(num)
      localStorage.setItem @id, 1
    else
      localStorage.setItem @id, num + 1
  
  minus: ->
    getstr = localStorage.getItem(@id)
    num = parseInt(getstr, 10)
    if isNaN(num)
      localStorage.setItem @id, -1
    else
      localStorage.setItem @id, num - 1

###################################
#ぷらまいクラスを利用して表示とかできるようにした奴
class Cpm_tom
  constructor: ->
    @strdisp = new Disp("str")
    @converter = new showdown.Converter()
    @cpm = new Cpm("memo_num")
    
    key = localStorage.getItem("memo_num")
    #文字列を数字に変換
    num = parseInt(key, 10)
    for i in [0..num]
      @strdisp.add(localStorage.getItem(i))
  
  save:(@input) ->
    @cpm.plus()
    input_word = document.getElementById(@input).value
    mark2html = @converter.makeHtml(input_word)
    
    key = localStorage.getItem("memo_num")
    num = parseInt(key, 10)
    localStorage.setItem num, mark2html
    @strdisp.delete()
    for i in [0..num]
      @strdisp.add(localStorage.getItem(i))
      
      
###############################
class Select_strage
  constructor:(@input_key, @input_value) ->
    
  story1:(@key, @value) ->
    document.getElementById(@input_key).value
    localStorage.setItem @key, @value
    
  story2: ->
    key = document.getElementById(@input_key).value
    value = document.getElementById(@input_value).value
    localStorage.setItem key, value

################################
class Add_radio
  constructor:(@div, @name) ->
    @strdisp = new Disp(@div)

  add:(@value, @disp_name) ->
    @strdisp.add("
    <label class=\"item item-radio ng-empty ng-valid\" name=\"#{@name}\" ng-model=\"choice\" ng-value=\"\'#{@value}\'\" value=\"#{@value}\" style=\"\">
    <input type=\"radio\" name=\"#{@name}\" ng-value=\"\'#{@value}\'\" ng-model=\"choice\" class=\"ng-pristine ng-untouched ng-valid ng-empty\" value=\"#{@value}\" style=\"\">
    <div class=\"radio-content\">
    <div class=\"item-content disable-pointer-events\" ng-transclude=\"\">
    <span>#{@disp_name}</span>
    </div>
    <i class=\"radio-icon disable-pointer-events icon ion-checkmark\">
    </i>
    </div>
    </label>
    ")
  
  delete: ->
    this.delete()
  
  story1: ->
      key = localStorage.getItem("memo_num")
      num = parseInt(key, 10)
      for i in [1..num]
        this.add(i ,localStorage.getItem(i))
  
  story2: ->
    $("#"+"#{@div}").click =>
      value = $('input[name=betu]:checked').val()
      key = "getradio"
      localStorage.setItem key, value
  
  story3: ->
    console.log "input[name=#{@name}]"
    doAfter = ->
      radionum = localStorage.getItem("getradio")
      $("input[name=betu]").val [radionum]
    setTimeout(doAfter, 10)
      
##################################
class Select_memo_disp
  constructor:(@div) ->
    @disp = new Disp(@div)
    @value = localStorage.getItem("getradio")
    @value2 = localStorage.getItem(@value)
    @disp.disp(@value2)
    
#############################
class Add_title
  constructor:(@input, @add_button)->
    @cpm = new Cpm("memo_num")
    $("##{@add_button}").click =>
      console.log "add title"
      @const = document.getElementById(@input).value
      console.log @const
  
  #あまりセンスがない書き方してるので気を付けるべし
  story1: ->
    @cpm.plus()
    console.log "story1"
    key = localStorage.getItem("memo_num")
    console.log num = parseInt(key, 10)
    @title = document.getElementById(@input).value
    localStorage.setItem num, @title
    
    new Disp("accountdisp").delete()
    addradio = new Add_radio("accountdisp", "betu")
    addradio.story1()
    addradio.story2()
    addradio.story3()
    

##################
class Delete_button
  constructor:->
    console.log "delete ok"
      
#################
class Edit_memo
  constructor:->
    console.log "constructor"
    @test1 = document.getElementById("inputdesu").value
    @test2 = localStorage.getItem("getradio")
    @test3 = localStorage.getItem(@test2)
    document.getElementById("inputdesu").value = @test3
  save: ->
    console.log "story1"
    @test4 = document.getElementById("inputdesu").value
    @test5 = localStorage.getItem("getradio")
    localStorage.setItem @test5, @test4
    

#ここに本来controllers.coffeeである記述を行う

angular.module('starter.controllers', [])
.controller('DashCtrl', ($scope) ->
  cpm = new Cpm("memumu")
  sele = new Select_strage("key", "value")
  
  $scope.$on '$ionicView.enter', (event, data) ->
    alert "入場時自動起動"
  
  doAfter = ->
    radionum = localStorage.getItem("getradio")
    $("input[name=hoge]").val [radionum]
  setTimeout(doAfter, 100)
  
  $scope.plus = () =>
    cpm.plus()
  
  $scope.minus = () =>
    cpm.minus()
    
  $scope.change = () =>
    sele.story2()
    #alert 1
    
  $scope.getradio = =>
    @value = $('input[name=hoge]:checked').val()
    @key = "getradio"
    localStorage.setItem @key, @value
    
)

.controller('TestCtrl', ($scope) ->
  cpm_tom = new Cpm_tom()
  edit_memo = new Edit_memo()
  $scope.$on '$ionicView.enter', (event, data) ->
    edit_memo = new Edit_memo()

  $scope.save = () =>
    #cpm_tom.save("inputdesu")
    
    edit_memo.save()
      
      
)

.controller('ChatsCtrl', ($scope) ->
  $scope.$on '$ionicView.enter', (event, data) ->
    new Select_memo_disp("str33")
    
  
)

.controller 'AccountCtrl', ($scope) ->
  $scope.$on '$ionicView.enter', (event, data) ->
    new Disp("accountdisp").delete()
    addradio = new Add_radio("accountdisp", "betu")
    addradio.story1()
    addradio.story2()
    addradio.story3()
  $("#add_title").click =>
    test111 = new Add_title("input_title")
    test111.story1()
  $("#delete").click =>
    new Delete_button()

# ---
# generated by js2coffee 2.2.0s